name: test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:6.0
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test -c release
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest
          - latest-stable
    runs-on: macos-latest
    steps:
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Check out
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test -c release
